application.affiliation/Controllers/formDataController.cs
using application.affiliation.BE;
using application.affiliation.Models;
using application.affiliation.VM;
using Microsoft.Ajax.Utilities;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace application.affiliation.Controllers
{
    public class formDataController : Controller
    {
        // GET: formData
        public ActionResult Index()
        {
            formDataVM objFormDataVM = new formDataVM();
            objFormDataVM.objUserDetailList = new List<UserDetail>();
            return View("index", objFormDataVM);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult searchMobileNo(formDataVM objFormDataVM)
        {
            AffiliationPanelEntities db = new AffiliationPanelEntities();
            formDataVM objFormDataResponseVM = new formDataVM();
            string filePath = string.Empty;
            if (objFormDataVM.postedFile != null)
            {
                string path = Server.MapPath("~/Uploads/");
                if (!Directory.Exists(path))
                {
                    Directory.CreateDirectory(path);
                }

                filePath = path + Path.GetFileName(objFormDataVM.postedFile.FileName);
                string extension = Path.GetExtension(objFormDataVM.postedFile.FileName);
                objFormDataVM.postedFile.SaveAs(filePath);

                //Read the contents of CSV file.
                string csvData = System.IO.File.ReadAllText(filePath).Replace("\r\n", ",").Replace("MobileNo", "");
                string[] arrCSVData = csvData.Split(',');
                arrCSVData = arrCSVData.Where(x => !string.IsNullOrEmpty(x)).ToArray();

                Nullable<DateTime> dFromDate = String.IsNullOrEmpty(objFormDataVM.FromDate) ? (DateTime?)null : new DateTime(Convert.ToInt32(objFormDataVM.FromDate.Split('-')[2]), Convert.ToInt32(objFormDataVM.FromDate.Split('-')[1]), Convert.ToInt32(objFormDataVM.FromDate.Split('-')[0]), 0, 0, 0);
                Nullable<DateTime> dToDate = String.IsNullOrEmpty(objFormDataVM.ToDate) ? (DateTime?)null : new DateTime(Convert.ToInt32(objFormDataVM.ToDate.Split('-')[2]), Convert.ToInt32(objFormDataVM.ToDate.Split('-')[1]), Convert.ToInt32(objFormDataVM.ToDate.Split('-')[0]), 23, 0, 0);
                if (dFromDate != null && dToDate != null)
                    objFormDataResponseVM.objUserDetailList = db.UserDetail.Where(x => arrCSVData.Contains(x.MobileNo.ToString()) && (x.CreatedDate >= dFromDate && x.CreatedDate <= dToDate)).ToList();
                else
                    objFormDataResponseVM.objUserDetailList = db.UserDetail.Where(x => arrCSVData.Contains(x.MobileNo.ToString())).ToList();
                objFormDataResponseVM.filterRecords = objFormDataResponseVM.objUserDetailList.Count();
                objFormDataResponseVM.totalRecords = db.UserDetail.Count();
                return View("index", objFormDataResponseVM);
            }
            else
            {
                TempData[Helper.responseStatus] = "1|Please select and upload csv file";
                return View("index", objFormDataResponseVM);
            }
        }
    }
}

application.affiliation/Views/formData/index.cshtml
@model  application.affiliation.VM.formDataVM
@{
    ViewBag.Title = "form Data";
    Layout = "~/Views/Shared/_Layout.cshtml";
    @Styles.Render("~/bundles/datatablescss")
    <style>
        .table.table-sm th, .table.table-sm td {
            padding: 0.3rem 1rem;
        }

        .btn-sm {
            padding: 0.5rem 0.5rem;
        }
    </style>
}
<link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
<link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/timepicker/1.3.5/jquery.timepicker.min.css">
<section id="row-separator-form-layouts">
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header text-center">
                    <h1 class="card-title">Search Data via Mobile No.</h1>
                </div>
                <div class="card-content">
                    <div class="card-body">
                        @using (Html.BeginForm("searchMobileNo", "formData", FormMethod.Post, new { enctype = "multipart/form-data" }))
                        {
                            @Html.AntiForgeryToken();
                            <div class="form-body">
                                <div class="form-group row mx-auto">
                                    <label class="label-control col-md-3">Start Date</label>
                                    <div class="col-md-2">
                                        @Html.EditorFor(model => model.FromDate, new { htmlAttributes = new { @class = "form-control form-control-md", @placeholder = "Enter From Date", @id = "fromDate" } })
                                    </div>
                                    <label class="label-control col-md-2 text-right">End Date</label>
                                    <div class="col-md-2">
                                        @Html.EditorFor(model => model.ToDate, new { htmlAttributes = new { @class = "form-control form-control-md", @placeholder = "Enter To Date", @id = "toDate" } })
                                    </div>
                                </div>
                                <div class="form-group row mx-auto pt-2">
                                    <label class="label-control col-md-3">Upload CSV File</label>
                                    <div clsas="col-md-3">
                                        <input type="file" name="postedFile" accept=".csv" />
                                    </div>
                                    <div class="col-md-2">
                                        <button type="submit" class="btn btn-primary waves-effect waves-light" id="btnSubmit">
                                            Submit
                                        </button>
                                    </div>
                                    <div class="col-md-3">
                                        <a href="~/searchbymobile.csv" download="~/searchbymobile.csv">Download CSV Search file format</a>
                                    </div>
                                </div>
                            </div>
                        }
                        @if (Model != null)
                        {
                            if (Model.objUserDetailList != null)
                            {
                                <hr />
                                <div class="form-body pt-2">
                                    <div class="form-group row mx-auto">
                                        <div class="text-right col-md-12">
                                            <h2 class="text-danger"><strong>@Model.filterRecords.ToString() / @Model.totalRecords Excel Records Matched</strong></h2>
                                        </div>
                                    </div>
                                    <div class="table-responsive">
                                        <table class="table table-sm font-small-3 table-bordered text-center table-responsive-md table-striped btn-lighten-1" id="tblDataList">
                                            <thead>
                                                <tr>
                                                    <th class="text-center">Email</th>
                                                    <th class="text-center">Mobile No</th>
                                                    <th class="text-center">Bank</th>
                                                    <th class="text-center">Account No</th>
                                                    <th class="text-center">Account Holder Name</th>
                                                    <th class="text-center">IFSC Code</th>
                                                    <th class="text-center">Created Date</th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                                @foreach (application.affiliation.Models.UserDetail userData in Model.objUserDetailList)
                                                {
                                                    <tr>
                                                        <td class="text-center">@userData.Email</td>
                                                        <td class="text-center">@userData.MobileNo</td>
                                                        <td class="text-center">@userData.BankName</td>
                                                        <td class="text-center">@userData.BankAccNo</td>
                                                        <td class="text-center">@userData.AccountHolderName</td>
                                                        <td class="text-center">@userData.BankIFSC</td>
                                                        <td class="text-center">@userData.CreatedDate</td>
                                                    </tr>
                                                }
                                            </tbody>
                                        </table>
                                    </div>
                                </div>
                            }
                            else
                            {
                                <div class="text-center">
                                    <h2>No Record Found!</h2>
                                </div>
                            }
                        }
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
@section scripts{
    @Scripts.Render("~/bundles/jqueryval");
    @Scripts.Render("~/bundles/datatables");
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/timepicker/1.3.5/jquery.timepicker.min.js"></script>
    <script>
        $(function () {
            var showMessage = '@TempData[application.affiliation.BE.Helper.responseStatus]'
             if (showMessage != '')
                 notifyMessage(showMessage);

             var dateFormat = "dd-mm-yy",
                from = $("#fromDate")
                    .datepicker({
                        dateFormat:"dd-mm-yy",
                        defaultDate: "+1w",
                        changeMonth: true,
                        numberOfMonths: 2
                    })
                    .on("change", function () {
                        to.datepicker("option", "minDate", getDate(this));
                    }),
                to = $("#toDate").datepicker({
                    dateFormat:"dd-mm-yy",
                    defaultDate: "+1w",
                    changeMonth: true,
                    numberOfMonths: 2
                })
                    .on("change", function () {
                        from.datepicker("option", "maxDate", getDate(this));
                    });

            function getDate(element) {
                var date;
                try {
                    date = $.datepicker.parseDate(dateFormat, element.value);
                } catch (error) {
                    date = null;
                }

                return date;
            }
         });

        $(document).ready(function () {
            $("#tblDataList").DataTable({
                dom: 'Blfltip',
                buttons: [
                    ['csv'],
                ],
                lengthMenu: [
                    [50, 100, 500, 1000, 2000, -1],
                    ['50 rows', '100 rows', '500 rows', '1000 rows', '2000 rows', 'All rows']
                ]
            });
            $("#tblDataList_length").hide();
        });
    </script>
}